### ISSUE TITLE
Command lines needed to compile each chapter?

### ISSUE THREAD

**Issue by Xamtastic** [PacktPublishing/Hands-On-Game-Development-with-WebAssembly#1]
Could you please put the command lines that are needed to compile each chapter, into a page that we can cut and paste from. They are quite long and the online book (which cost me 20 quid) has disabled the capacity to cut and paste the command lines.

Here's Chapter 14, which I've tested, great game!
```
em++ asteroid.cpp audio.cpp camera.cpp collider.cpp emitter.cpp enemy_ship.cpp finite_state_machine.cpp locator.cpp main.cpp particle.cpp player_ship.cpp projectile_pool.cpp projectile.cpp range.cpp render_manager.cpp shield.cpp ship.cpp star.cpp ui_button.cpp ui_sprite.cpp vector.cpp -o ui.html --preload-file audio --preload-file sprites -std=c++17 -s USE_WEBGL2=1 -s USE_SDL=2 -s USE_SDL_IMAGE=2 -s SDL2_IMAGE_FORMATS=["png"] -s USE_SDL_IMAGE=2 -s SDL2_IMAGE_FORMATS=["png"]
```

**Comment by sarvesh-packt** [comment]
Hi Xamtastic,

Apologies for the inconvenience caused. We will definitely try to provide such command files in our future titles.
I hope the Copy/Paste issue is resolved! If not please re-open the issue.

Regards,
