### ISSUE TITLE
initial sprite render error - unsupported file format

### ISSUE THREAD

**Issue by thodges314** [PacktPublishing/Hands-On-Game-Development-with-WebAssembly#2]
I'm getting the following error from sprite.c (chapter 4):
_failed to load image: Unsupported image format_
I am using the following command to compile, since no other details are given:
`emcc sprite.c --preload-file sprites -s USE_SDL=2 -s USE_SDL_IMAGE=2 -o sprite.html`
Should I be doing something else?

**Comment by battlelinegames** [comment]
I'm sorry I'm only now seeing this.  What page were you on when you ran into trouble?  

Thanks

**Comment by deepesh-packt** [comment]
Please reopen the issue if the issue still persists 👍
